//
//  AuthenticationOperation.swift
//  AltStore
//
//  Created by Riley Testut on 6/5/19.
//  Copyright © 2019 Riley Testut. All rights reserved.
//

@preconcurrency import UIKit
import Foundation
import Network
import CoreData
import SideSign

enum RevokeDecision: Sendable {
    case revokeSelected([ALTX509Certificate])
    case keepExisting
}

typealias AuthenticationError = AuthenticationErrorCode.Error
enum AuthenticationErrorCode: Int, ALTErrorEnum, CaseIterable {
    case noTeam
    case noCertificate
    case teamSelectorError
    
    case missingPrivateKey
    case missingCertificate
    
    case certificateLimitReachedFree
    case certificateLimitReachedPaid
    
    var errorFailureReason: String {
        switch self {
        case .noTeam: return NSLocalizedString("Your Apple ID has no developer teams?", comment: "")
        case .noCertificate: return NSLocalizedString("The developer certificate could not be found.", comment: "")
        case .teamSelectorError: return NSLocalizedString("Error presenting team selector view.", comment: "")
        case .missingPrivateKey: return NSLocalizedString("The certificate's private key could not be found.", comment: "")
        case .missingCertificate: return NSLocalizedString("The certificate could not be found.", comment: "")
        case .certificateLimitReachedFree: return NSLocalizedString("You have already exhausted the limit of 1 certificate for free developer accounts. Please revoke the existing certificate and try again.", comment: "")
        case .certificateLimitReachedPaid: return NSLocalizedString("You have already exhausted the maximum certificates that can be generated by a paid developer account. Please revoke at least one certificate and try again.", comment: "")
        }
    }
}

struct AuthenticationResult {
    let team: ALTTeam
    let certificate: ALTCertificate?
    let session: ALTAppleAPISession
    let portalCertificates: [ALTX509Certificate]?
}

private struct SessionCache {
    let team: ALTTeam
    let session: ALTAppleAPISession
}

final class AuthenticationOperation: BaseStandaloneOperation<AuthenticatedOperationContext, AuthenticationResult>, @unchecked Sendable {
    
    private var appleIDEmailAddress: String?
    private var requiresPostAuthFlow = false
    private var lastFetchedAnisetteData: ALTAnisetteData?
    
    let skipDeviceRegistration: Bool
    let skipCertificateProvisioning: Bool

    init(context: AuthenticatedOperationContext, skipDeviceRegistration: Bool = false, skipCertificateProvisioning: Bool = false) throws {
        self.skipDeviceRegistration = skipDeviceRegistration
        self.skipCertificateProvisioning = skipCertificateProvisioning

        try super.init(context: context)
        self.debugLog("""
        [AuthenticationOperation] Initialized with options:
          • skipDeviceRegistration: \(skipDeviceRegistration)
          • skipCertificateProvisioning: \(skipCertificateProvisioning)
        """)
    }

    private func getAnisetteData(for session: ALTAppleAPISession? = nil) async throws -> ALTAnisetteData {
        let currentAnisette = session?.anisetteData ?? self.lastFetchedAnisetteData
        if let currentAnisette = currentAnisette,
           currentAnisette.date.timeIntervalSinceNow >= -AnisetteProvider.validDuration {
            return currentAnisette
        }

        let anisetteData = try await AnisetteProvider.fetch(handler: context.anisetteServerHandler)
        self.lastFetchedAnisetteData = anisetteData
        return anisetteData
    }
    
    // Main Pipeline Execution
    override func execute(parentProgress: Progress?) async throws -> AuthenticationResult {
        let startTime = CFAbsoluteTimeGetCurrent()
        debugLog("[AuthenticationOperation] execute() started")
        defer {
            let elapsed = CFAbsoluteTimeGetCurrent() - startTime
            debugLog("[AuthenticationOperation] execute() took: \(String(format: "%.3fs", elapsed))")
        }
        try await super.executePreconditionCheck(parentProgress: parentProgress)

        let authResult = try await TaskChainCoalescerWithProgress.shared.coalesce(
            key: "apple_auth",
            onProgress: { [weak self] progress in
                self?.setProgress(progress)
            }
        ) { [weak self] reportProgress -> AuthenticationResult in
            guard let self = self else { throw OperationError.cancelled }
            
            do {
                let result: AuthenticationResult

                if var session = AuthManager.shared.session,
                   let team = AuthManager.shared.team,
                   (self.skipCertificateProvisioning || CertificateManager.shared.activeCertificate != nil)
                {
                    session.anisetteData = try await self.getAnisetteData(for: session)
                    let certToUse = CertificateManager.shared.activeCertificate?.certificate
                    
                    self.debugLog("[Authentication] Using cached session, team, certificate")
                    result = AuthenticationResult(
                        team: team, 
                        certificate: certToUse, 
                        session: session, 
                        portalCertificates: self.context.portalCertificates
                    )
                } else {
                    result = try await self.startAuthentication(reportProgress: reportProgress)
                }
                
                try await self.finalizeAuthentication(result: .success(result))
                reportProgress(100)
                return result
            } catch {
                self.debugLog("[AuthenticationOperation] execute caught error during authentication: \(error). Cleaning up...")
                // if auth was good, but certs and others had errors don't signOut ourselves.
                if !AuthManager.shared.hasStoredPassword &&
                   !AuthManager.shared.hasStoredXcodeToken
                {
                    AuthManager.shared.signOut()
                }
                try? await self.finalizeAuthentication(result: .failure(error))
                throw error
            }
        }
        
        self.context.team               = authResult.team
        self.context.signingCertificate = authResult.certificate
        self.context.session            = authResult.session
        self.context.portalCertificates = authResult.portalCertificates

        self.setProgress(100)
        return authResult
    }
    
    private func startAuthentication(reportProgress: @escaping @Sendable (Int64) -> Void) async throws -> AuthenticationResult {
        let (account, session) = if let silentResult = try await self.silentSignIn() {
            silentResult
        } else {
            try await self.authenticationLoop()
        }
        self.context.session = session
        AuthManager.shared.session = session

        let authResult = try await self.provisioningLoop(
            account: account,
            session: session,
            reportProgress: reportProgress
        )
        
        return authResult
    }

    private func provisioningLoop(account: ALTAccount,
                                  session: ALTAppleAPISession,
                                  reportProgress: @escaping @Sendable (Int64) -> Void) async throws -> AuthenticationResult
    {
        
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        reportProgress(stepWeight)

        var resolvedTeam: ALTTeam?
        var resolvedCertificate: ALTCertificate?

        var isCertificateResolved = false
        var isDeviceRegistered = false

        while true {
            if self.isCancelled { throw OperationError.cancelled }

            do {
                // 1. Resolve Team & Save State
                if resolvedTeam == nil {
                    let team = try await self.fetchTeam(for: account, session: session)

                    self.context.team = team
                    AuthManager.shared.team = team

                    try await self.saveTeamAndAccount(team)
                    reportProgress(stepWeight * 2)
                    resolvedTeam = team
                }

                guard let team = resolvedTeam else { continue }

                // 2. Resolve Certificate (Custom vs Developer Portal)
                if !isCertificateResolved {
                    let activeCert = CertificateManager.shared.activeCertificate?.certificate
                    let isCustomCert = activeCert?.data.map { data in
                        let details = parseCertificate(derData: data)
                        return !details.subject.contains(team.identifier) && !details.issuer.contains(team.identifier)
                    } ?? false
                    if isCustomCert {
                        self.debugLog("[Authentication] Custom active certificate detected (Subject OU mismatch with Team ID '\(team.identifier)'). Bypassing portal fetch.")
                        resolvedCertificate = activeCert
                    } else if self.skipCertificateProvisioning {
                        resolvedCertificate = activeCert
                    } else {
                        let certificate = try await self.fetchCertificate(for: team, session: session)
                        try CertificateManager.shared.setActiveCertificate(certificate)
                        self.context.signingCertificate = certificate
                        resolvedCertificate = certificate
                    }
                    isCertificateResolved = true
                }

                guard isCertificateResolved else { continue }

                // 3. Register Current Device
                if !isDeviceRegistered {
                    if !self.skipDeviceRegistration {
                        self.verboseLog("[Authentication] Registering current device...")
                        let device = try await self.registerCurrentDevice(for: team, session: session)
                        self.debugLog("[Authentication] Registered current device UDID: \(device.identifier).")
                        reportProgress(stepWeight * 3)
                    }
                    isDeviceRegistered = true
                }

                return AuthenticationResult(
                    team: team,
                    certificate: resolvedCertificate,
                    session: session,
                    portalCertificates: self.context.portalCertificates
                )
                
            } catch {
                if self.isCancelled { throw OperationError.cancelled }

                self.debugLog("[AuthenticationOperation] provisioningLoop caught error: \(error)")
                let decision = await self.context.authenticationHandler.resolveProvisioningError(error)
                switch decision {
                    case .retry:
                        self.debugLog("[AuthenticationOperation] User chose retry in provisioningLoop")
                        continue
                    case .cancel:
                        self.debugLog("[AuthenticationOperation] User cancelled in provisioningLoop")
                        throw OperationError.cancelled
                }
            }
        }
    }
    
    private func silentSignIn() async throws -> (ALTAccount, ALTAppleAPISession)? {
        // Try silent auth using Keychain Token
        if let adsid = AuthManager.shared.adsid, 
           let xcodeToken = AuthManager.shared.xcodeToken 
        {
            self.verboseLog("[AuthenticationOperation] Authenticating Apple ID with tokens...")

            do {
                let anisetteData = try await self.getAnisetteData()
                let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()

                return try await AuthManager.shared.authenticateWithToken(
                    adsid: adsid,
                    xcodeToken: xcodeToken, 
                    anisetteData: anisetteData, 
                    xcodeVersion: xcodeVersion
                )
            } catch {
                self.debugLog("[AuthenticationOperation] Token authentication failed: \(error)")
            }
        }
        
        // Try silent auth using Keychain Password
        if let appleID = AuthManager.shared.currentAppleID, 
           let password = AuthManager.shared.password 
        {
            self.debugLog("[AuthenticationOperation] Authenticating Apple ID with saved password...")
            do {
                return try await self.authenticate(appleID: appleID, password: password)
            } catch {
                self.debugLog("[AuthenticationOperation] Saved password authentication failed: \(error)")
            }
        }

        return nil
    }

    private func authenticationLoop() async throws -> (account: ALTAccount, session: ALTAppleAPISession) {
        self.verboseLog("[Authentication] authenticationLoop: Requesting credentials...")
        let handler = self.context.authenticationHandler
        
        while true {
            let (appleID, password) = try await handler.credentials()
            if self.isCancelled { throw OperationError.cancelled }
            
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.debugLog("[Authentication] authenticationLoop: authenticate succeeded.")
                
                await handler.handleSignInResult(.success((account, session)))
                
                self.requiresPostAuthFlow = true
                return (account, session)
            } catch {
                self.debugLog("[Authentication] authenticationLoop: Attempt failed with error: \(error)")
                await handler.handleSignInResult(.failure(error))
            }
        }
    }
    
    private func authenticate(appleID: String, password: String) async throws -> (ALTAccount, ALTAppleAPISession) {
        self.appleIDEmailAddress = appleID
        
        let anisetteData = try await self.getAnisetteData()
        let handler = self.context.authenticationHandler
        
        let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()

        let (account, session) = try await AuthManager.shared.authenticate(
            appleID: appleID,
            password: password,
            anisetteData: anisetteData,
            xcodeVersion: xcodeVersion,
            accountRepairHandler: { url, message in
                await handler.accountRepair(url: url, message: message)
            },
            verificationHandler: { request in
                try await handler.verificationCode(for: request)
            }
        )
        
        AuthManager.shared.adsid = session.dsid
        AuthManager.shared.xcodeToken = session.authToken
        AuthManager.shared.currentAppleID = appleID
        AuthManager.shared.password = password
        
        return (account, session)
    }


    private func finalizeAuthentication(result: Result<AuthenticationResult, Error>) async throws {
        self.verboseLog("[Authentication] finalizeAuthentication: Starting cleanup...")
        
        switch result {
            case .failure(let error):
                self.debugLog("[Authentication] finalizeAuthentication: Failure result - \(error.localizedDescription)")
                await self.context.authenticationHandler.complete()
                self.verboseLog("[Authentication] finalizeAuthentication: invoked auth complete for .failure case...")
                
            case .success(let result):
                let team = result.team
                let certificate = result.certificate
                let session = result.session

                self.verboseLog("[Authentication] finalizeAuthentication: Authentication Success for team \(team.identifier) account.")
                do {
                    try await self.saveTeamAndAccount(team, makeActive: true)
                } catch {
                    self.debugLog("[Authentication] finalizeAuthentication: error occured when performing cleanup: \(error)")
                }
                self.verboseLog("[Authentication] finalizeAuthentication: Database updates completed.")
                
                if let signingCertificate = certificate, !self.skipCertificateProvisioning
                {
                    let signer = ALTSigner(team: team, certificate: signingCertificate)
                    let didResign = await self.validateCodeSign(signer: signer, session: session)
                    self.verboseLog("[Authentication] finalizeAuthentication: didResign = \(didResign)")
                    
                    if !didResign && self.requiresPostAuthFlow {
                        await self.context.authenticationHandler.resolvePostAuth()
                        self.verboseLog("[Authentication] finalizeAuthentication: post auth flow completed...")
                    }
                }
                
                await self.context.authenticationHandler.complete()
                self.verboseLog("[Authentication] finalizeAuthentication: invoked auth complete for .success case...")
        }
    }
}

// Persistence and Codesign Validity Check Helpers
private extension AuthenticationOperation {

    private func saveTeamAndAccount(_ altTeam: ALTTeam, makeActive: Bool = false) async throws {
        guard let context = self.context.dbBackgroundContext else {
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        try await context.perform {
            let account: Account
            let team: Team
            
            let accountIdentifier = altTeam.account?.identifier ?? altTeam.identifier
            if let tempAccount = Account.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Account.identifier), accountIdentifier), in: context) {
                account = tempAccount
            } else if let altAccount = altTeam.account {
                account = Account(altAccount, context: context)
            } else {
                let altAccount = ALTAccount(appleID: self.appleIDEmailAddress ?? "", identifier: accountIdentifier)
                account = Account(altAccount, context: context)
            }
            
            if let tempTeam = Team.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Team.identifier), altTeam.identifier), in: context) {
                team = tempTeam
            } else {
                team = Team(altTeam, account: account, context: context)
            }
            
            if let altAccount = altTeam.account {
                account.update(account: altAccount)
            }

            if let providedEmailAddress = self.appleIDEmailAddress {
                account.appleID = providedEmailAddress
            }
            
            team.update(team: altTeam)
            
            if makeActive {
                // Account
                account.isActiveAccount = true
                let otherAccountsFetchRequest = Account.fetchRequest() as NSFetchRequest<Account>
                otherAccountsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Account.identifier), account.identifier)
                let otherAccounts = try context.fetch(otherAccountsFetchRequest)
                for otherAccount in otherAccounts {
                    otherAccount.isActiveAccount = false
                }

                // Team
                team.isActiveTeam = true
                let otherTeamsFetchRequest = Team.fetchRequest() as NSFetchRequest<Team>
                otherTeamsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Team.identifier), team.identifier)
                let otherTeams = try context.fetch(otherTeamsFetchRequest)
                for otherTeam in otherTeams {
                    otherTeam.isActiveTeam = false
                }

                let isSparseRestorePatched   = ProcessInfo().sparseRestorePatched
                let isAppLimitDisabled       = UserDefaults.standard.isAppLimitDisabled

                UserDefaults.standard.activeAppsLimit = nil
                // TODO: @mahee96: is the minimum ver match for ios 13.3.1 check required?
                //                 if so what is the app limit? As nil app limit specifies unlimited apps?!
                if team.type == .free {
                    if !isAppLimitDisabled && isSparseRestorePatched ||
                        isAppLimitDisabled && !isSparseRestorePatched 
                    {
                        UserDefaults.standard.activeAppsLimit = InstalledApp.freeAccountActiveAppsLimit
                    }
                }
            }
            
            try context.save()
        }
    }
    
    private func validateCodeSign(signer: ALTSigner, session: ALTAppleAPISession) async -> Bool {
        self.verboseLog("[Authentication] validateCodeSign: entering method")
        guard let appBundle = ALTApplication(fileURL: Bundle.Info.activeBundleURL), 
              let provisioningProfile = appBundle.provisioningProfile else 
        {
            self.verboseLog("[Authentication] validateCodeSign: Application bundle or provisioning profile nil, returning false")
            return false
        }
        
        let result = CodeSignValidator.validate(
            runningProfile: provisioningProfile,
            portalCertificates: self.context.portalCertificates,
            signerCertificate: signer.certificate.x509,
            signerTeam: signer.team
        )
        
        switch result {
            case .success:
                self.verboseLog("[Authentication] validateCodeSign: Validation succeeded, no resign required.")
                return false
                
            case .failure(let reason):
                self.debugLog("[Authentication] Signing certificate mismatch detected: \(reason)")
                
                // For Paid Developer accounts, if the certificate used to sign the current installation
                // is still active on Apple's portal (which shows as .privateKeyLost or .externalSigner),
                // we don't need to warn the user or force a resign.
                if signer.team.type != .free && (reason == .privateKeyLost || reason == .externalSigner) {
                    self.debugLog("[Authentication] Running certificate is still active on the Paid account portal. Skipping resign screen.")
                    return false
                }
                
                let handler = self.context.authenticationHandler
                do {
                    return try await handler.resolveResign(mismatchReason: reason, context: self.context)
                } catch {
                    self.verboseLog("[Authentication] validateCodeSign: error occured when handling resolveResign error: \(error)")
                    return false
                }
        }
    }
}


// Team, Certificate Resolution & Device Registration Helpers
private extension AuthenticationOperation {

    private func fetchTeam(for account: ALTAccount, session: ALTAppleAPISession) async throws -> ALTTeam {
        self.verboseLog("[Authentication] fetchTeam: Requesting teams from Apple...")
        let teams = try await DeveloperPortalService.shared.fetchTeams(for: account, session: session)
        
        var activeTeamFromDB: Team?
        if let dbContext = self.context.dbBackgroundContext {
            activeTeamFromDB = await dbContext.perform {
                DatabaseManager.shared.activeTeam(in: dbContext)
            }
        }
        
        let selectedTeam: ALTTeam
        if let activeTeam = activeTeamFromDB, let altTeam = teams.first(where: { $0.identifier == activeTeam.identifier }) {
            selectedTeam = altTeam
        } else if teams.count <= 1 {
            if let team = teams.first {
                selectedTeam = team
            } else {
                throw AuthenticationError(.noTeam)
            }
        } else {
            selectedTeam = try await self.context.authenticationHandler.resolveTeam(teams)
        }
        
        self.debugLog("[Authentication] fetchTeam completed successfully ('\(selectedTeam.name)').")
        return selectedTeam
    }

    private func fetchCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let portalCertificates = try await DeveloperPortalService.shared.fetchCertificates(team: team, session: session)
        self.context.portalCertificates = portalCertificates
        
        let mainBundleCertSerial = Bundle.main.object(forInfoDictionaryKey: Bundle.Info.certificateID) as? String
        
        if let activeCert = CertificateManager.shared.activeCertificate,
           let certificate = portalCertificates.first(where: { $0.serialNumber == activeCert.serialNumber }) 
        {
            var keyStoreCert = activeCert.certificate
            keyStoreCert.machineIdentifier = certificate.machineIdentifier

            if let mainBundleCertSerial = mainBundleCertSerial, 
                mainBundleCertSerial.lowercased() != activeCert.serialNumber.lowercased() 
            {
                self.debugLog("[Authentication] Active certificate (\(activeCert.serialNumber)) and running bundle certificate (\(mainBundleCertSerial)) mismatch detected. Running Bundle Certificate is still active on the Paid account portal. Using active Keychain certificate.")
            }
            return keyStoreCert
        }
        
        // TODO: @mahee96: we have moved away from machineID as password for certs, but external/thirdparty like iloader might not have, 
        //                 so we still support the machineId as fallback for now 
        if let mainBundleCertSerial = mainBundleCertSerial,
           let certificate = portalCertificates.first(where: { $0.serialNumber.lowercased() == mainBundleCertSerial.lowercased() }),
           var cert = CertificateManager.shared.getSignableCertificate(for: mainBundleCertSerial, fallbackPassword: certificate.machineIdentifier) 
        {
            cert.machineIdentifier = certificate.machineIdentifier
            self.debugLog("[Authentication] Using running bundle certificate (\(cert.serialNumber)) with valid private key from signable cache.")
            return cert
        }
        
        if portalCertificates.isEmpty {
            // No portalCertificates, so request a new one.
            return try await self.requestCertificate(for: team, session: session)
        } else {
            // We don't have private keys for any of the portalCertificates,
            // so we need to revoke one and create a new one.
            return try await self.replaceCertificate(portalCertificates: portalCertificates, for: team, session: session)
        }
    }

    private func requestCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let deviceName = await UIDevice.current.name
        let accountName = team.account?.firstName ?? team.name
        let machineName: String = "SideStore - \(accountName)'s \(deviceName)"
        self.verboseLog("[Authentication] Requesting certificate for machineName '\(machineName)'...")

        do {
            let newPortalCertificate = try await DeveloperPortalService.shared.createCertificate(machineName: machineName, team: team, session: session)
            self.debugLog("[Authentication] Successfully requested new portal certificate (Serial: \(newPortalCertificate.serialNumber)).")
            
            // Apple's submitDevelopmentCSR response does not include raw certContent.
            // Fetch updated certificates list from portal to populate X509 certificate PEM data.
            let portalCertificates = try await DeveloperPortalService.shared.fetchCertificates(team: team, session: session)
            self.context.portalCertificates = portalCertificates

            let finalCert: ALTCertificate
            if let fullX509 = portalCertificates.first(where: { $0.serialNumber.lowercased() == newPortalCertificate.serialNumber.lowercased() }) {
                finalCert = ALTCertificate(x509: fullX509, privateKey: newPortalCertificate.privateKey)
            } else {
                finalCert = newPortalCertificate
            }

            return finalCert
        } catch {
            self.debugLog("[Authentication] requestCertificate: Failed with error: \(error)")
            if case .tooManyCertificates = error as? DeveloperPortalError {
                let friendlyError: AuthenticationError = (team.type == .free) 
                                        ? AuthenticationError(.certificateLimitReachedFree) 
                                        : AuthenticationError(.certificateLimitReachedPaid)

                let wrappedError = NSError(
                    domain: (friendlyError as NSError).domain,
                    code: (friendlyError as NSError).code,
                    userInfo: [
                        NSLocalizedDescriptionKey: friendlyError.localizedDescription,
                        NSLocalizedFailureReasonErrorKey: friendlyError.failureReason ?? "",
                        NSUnderlyingErrorKey: error as NSError
                    ]
                )
                throw wrappedError
            } else {
                throw error
            }
        }
    }

    private func replaceCertificate(portalCertificates: [ALTX509Certificate], for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        // Filter strictly for iOS Development certificates so Mac/Apple Development certs are never touched
        let iosCertificates = portalCertificates.filter { cert in
            let nameLower = cert.name.lowercased()
            return nameLower.contains("ios development") || nameLower.contains("iphone developer")
        }

        self.debugLog("[Authentication] replaceCertificate: Starting. Total certs on portal: \(portalCertificates.count), iOS Development certs: \(iosCertificates.count)")
        
        if iosCertificates.isEmpty {
            self.verboseLog("[Authentication] replaceCertificate: No iOS Development certificates found on portal. Requesting new...")
            return try await self.requestCertificate(for: team, session: session)
        }
        
        self.debugLog("[Authentication] replaceCertificate: Presenting revoke alert for \(iosCertificates.count) iOS Development cert(s)...")
        let action = try await self.context.authenticationHandler.resolveRevocation(certificates: iosCertificates, teamType: team.type)
        self.debugLog("[Authentication] replaceCertificate: User action was \(action)")
        switch action {
            case .keepExisting:
                self.verboseLog("[Authentication] replaceCertificate: Keeping existing, calling requestCertificate...")
                return try await self.requestCertificate(for: team, session: session)
                
            case .revokeSelected(let certsToRevoke):
                self.debugLog("[Authentication] replaceCertificate: Revoking \(certsToRevoke.count) selected certificate(s)...")
                var firstError: Error? = nil

                for certificate in certsToRevoke {
                    do {
                        self.verboseLog("[Authentication] replaceCertificate: Revoking certificate '\(certificate.machineName ?? certificate.name)' (Serial: \(certificate.serialNumber))...")
                        _ = try await DeveloperPortalService.shared.revokeCertificate(certificate, team: team, session: session)
                        self.verboseLog("[Authentication] replaceCertificate: Revoke succeeded.")
                    } catch {
                        self.debugLog("[Authentication] replaceCertificate: Revoke failed with error: \(error)")
                        if firstError == nil {
                            firstError = error
                        }
                    }
                }

                if let error = firstError {
                    self.debugLog("[Authentication] replaceCertificate: Error occurred during revocation, throwing...")
                    throw error
                } else {
                    self.debugLog("[Authentication] replaceCertificate: Selected certificates successfully revoked. Requesting new certificate...")
                    return try await self.requestCertificate(for: team, session: session)
                }
        }
    }
    
    @discardableResult
    private func registerCurrentDevice(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTDevice {
        self.debugLog("[Authentication] registerCurrentDevice starting...")
        var deviceUDID: String?
        do {
            await CellularRefreshManager.shared.turnOffDataIfNeeded()
            deviceUDID = try await fetchUDID()
            await CellularRefreshManager.shared.turnOnDataIfNeeded(addOnDelay: 2.0)
        } catch {
            await CellularRefreshManager.shared.turnOnDataIfNeeded(addOnDelay: 2.0)
            self.debugLog("[Authentication] fetchUDID failed: \(error)")
        }
        
        if deviceUDID == nil || deviceUDID?.isEmpty == true || deviceUDID == "XXXXX-XXXX-XXXXX-XXXX" {
            deviceUDID = try? await fetchUDID(useStatic: true)
        }
        
        guard let udid = deviceUDID, !udid.isEmpty, udid != "XXXXX-XXXX-XXXXX-XXXX" else {
            self.debugLog("[Authentication] Failed to fetch device UDID.")
            throw OperationError.unknownUDID
        }
        self.debugLog("[Authentication] Fetched device UDID: \(udid). Fetching team devices...")
        
        let devices = try await DeveloperPortalService.shared.fetchDevices(for: team, types: [.iphone, .ipad], session: session)
        if let device = devices.first(where: { $0.identifier == udid }) {
            self.debugLog("[Authentication] Device '\(device.name)' (UDID: \(udid)) is registered on team.")
            return device
        } else {
            let deviceName = await MainActor.run { UIDevice.current.name }
            self.debugLog("[Authentication] Registering new device '\(deviceName)' (UDID: \(udid))...")
            let device = try await DeveloperPortalService.shared.registerDevice(name: UIDevice.current.name, identifier: udid, type: .iphone, team: team, session: session)
            self.debugLog("[Authentication] Device '\(device.name)' (UDID: \(udid)) successfully registered.")
            return device
        }
    }
}


private enum AnisetteProvider {
    static let validDuration: TimeInterval = 40.0

    static func fetch(handler: AnisetteServerHandler) async throws -> ALTAnisetteData {
        if UserDefaults.standard.useOnDeviceAnisette {
            debugLog("[AuthenticationOperation] Fetching anisette via On-Device Anisette (ODA)...")
            return try await OnDeviceAnisetteManager.shared.fetchAnisetteData()
        } else {
            debugLog("[AuthenticationOperation] Fetching anisette via remote server...")
            return try await fetchRemote(handler: handler)
        }
    }

    private static func fetchRemote(handler: AnisetteServerHandler) async throws -> ALTAnisetteData {
        let serverUrlStrings = await AnisetteServersManager.shared.getActiveServerURLs()
        let servers = serverUrlStrings.compactMap { URL(string: $0) }
        guard !servers.isEmpty else {
            throw AnisetteError.noServersConfigured
        }

        let lastServer = UserDefaults.standard.menuAnisetteURL
        let startIndex = servers.firstIndex(where: { $0.absoluteString == lastServer }) ?? 0

        let provider = SideSign.AnisetteDataProvider.shared
        let existingBlob = AnisetteDataManager.shared.anisetteAdiBlob.flatMap { Data(base64Encoded: $0) }

        let (anisetteData, newAdiBlob) = try await provider.fetchAnisetteDataWithFailover(
            servers: UserDefaults.standard.disableAnisetteRotation ? [servers[startIndex]] : servers,
            startIndex: startIndex,
            existingAdiBlob: existingBlob,
            onError: { error in
                if case AnisetteError.outdatedV1Server(let serverURL, _) = error {
                    if UserDefaults.standard.defaultServerURL == serverURL.absoluteString {
                        return true
                    }
                    let shouldContinue = try await handler.warnOutdatedAnisetteServer()
                    if shouldContinue {
                        UserDefaults.standard.defaultServerURL = serverURL.absoluteString
                    }
                    return shouldContinue
                }
                return false
            },
            onSuccess: { successfulServer in
                UserDefaults.standard.menuAnisetteURL = successfulServer.absoluteString
                debugLog("[AuthenticationOperation] Successfully fetched Anisette data from \(successfulServer.absoluteString)")
            }
        )

        if let freshBlob = newAdiBlob {
            AnisetteDataManager.shared.anisetteAdiBlob = freshBlob.base64EncodedString()
        }

        return anisetteData
    }
}
